_GPL.j(function(f,d,gb,G,m,z,ma,t,W,Ha,K,Jb,Kb,Lb,na,O,g,hb,oa,ib,x,u,ic,v,Mb,Nb){function Ia(a,b,c){c=c||g;var e=!0;a&&f.each(a,function(d,f){return e=!!b.call(c,f,d,a)});return e}function Ob(a){var b=[];Ia(a,function(a){0>f.inArray(a,b,void 0)&&b.push(a);return!0});return b}function Ja(){}function Pb(a,b){return f(a).parents().is(b)}function Qb(a){return f(a).map(function(a,c){(a=c.parentNode)&&a.removeChild(c);return c}).toArray()}function Ka(a,b){function c(b){for(var c=a.split(".");b&&c.length;)b=
b[c.shift()];return b}if(a)return Pb(pa,n.body)||(pa=Qb('<iframe style="display:none;visibility:hidden"></iframe>')[0],n.body.appendChild(pa)),c(pa.contentWindow)||b||c(g)}function La(a){var b=(a=a||g.event)&&a.type;if(b&&(a.cancelBubble=!0,Ka("Event.prototype.stopImmediatePropagation",Ja).call(a),Ka("Event.prototype.stopPropagation",Ja).call(a),"beforeunload"!==b))return a.returnValue=!1,Ka("Event.prototype.preventDefault",Ja).call(a),!b}function X(a){a=Ha.userAgent.match(Jb(a+"[/ ](\\d+)","i"));
return(a&&a[1])|0}function Rb(a,b,c,e){var d=[];Ia(a,function(c,f){var g=b.call(this,c,f,a);(g!==O||e)&&d.push(g);return!0},c||g);return d}function Sb(a){a&&"object"===typeof a&&(a=f.extend.apply(f,arguments));return a}function w(a){var b={_:1E8*Math.random()|0},c="cdnstats-a.akamaihd.net/s.gif?";Ia(arguments,function(a){"string"===typeof a?c=a:Sb(b,"function"===typeof a?a(b):a);return!0});(new Image).src=t.protocol+"//"+c+Rb(b,function(a,b){if(null!==a&&a!==O)return z(na(b))+"="+z(na(a))}).join("&")}
function L(){return new m/1E3|0}function Ma(a,b,c){function d(a,b,c){try{return Object.defineProperty(a,b,c),!0}catch(e){return!1}}function h(a,b,c){try{if(Object.prototype.__defineGetter__)return"value"in c?a.__defineGetter__(b,function(){return c.value}):("get"in c&&a.__defineGetter__(b,c.get),"set"in c&&a.__defineSetter__(b,c.set)),!0;if("value"in c)return a[b]=c.value,!0}catch(d){}return!1}if(!qa)try{d({},"x",{}),qa=d}catch(f){qa=h}return qa(a,b,c)}function Y(){ga(n,oa,Y);Tb(function(a,b,c){ra=
a;Na=b;Z||(Z=!0,Oa=!1,Ub(),Vb(),Pa(),c&&f('<link rel="dns-prefetch" href="//'+c+'">').appendTo(n.getElementsByTagName("head")[0]||aa),sa=+new m,ta=f(g).scrollLeft(),ua=f(g).scrollTop(),A(n,oa,jb),A(g,"scroll",kb),A(g,"unload",lb),mb=Wb(function(){36E5<+new m-sa&&(w({t:"p_inactive",d:d.gd(),xr:+p,cid:l,pid:q,guid:d.guid,bf:k|0}),va(!1))},5E3))})}function Ub(){function a(a){var c=nb();B.attr({href:c,target:Qa()}).prop("src",c+"&"+d.B64.decode("ZGlzY2xvc2U="));return La(a)}B||(B=f('<a style="z-index:999999999999999;padding:0;margin:0;cursor:default;opacity:0.01;position:fixed;top:0;left:0;background:transparent;width:100%;height:100%;">&nbsp;</a>'),
A(B[0],"mousedown",a),A(B[0],"mouseup",La),A(B[0],"click",r),a());wa()}function jb(a){ha=[a.pageX,a.pageY,ta,ua];sa=+new m;wa()}function kb(){ta=f(g).scrollLeft();ua=f(g).scrollTop();sa=+new m;wa()}function va(a){Z&&(Z=!1,gb(mb),G(Ra),B.remove(),Xb(),ga(n,oa,jb),ga(n,"scroll",kb),ga(g,"unload",lb),Na=ra=O,P=Q="",Sa=!1,a||A(n,oa,Y),E(Y,1E3*W(R,H)))}function A(a,b,c){if(g[hb]){var d=xa();try{return d.call(a,b,c,!0)}catch(h){a[hb](b,c,!0)}}else a.attachEvent("on"+b,c)}function Vb(){ia=!0;d.ah(I,r);ba||
d.ah("keydown",r);d.ah("focus",r);ba&&d.ah("blur",r);try{var a=n.createElement("iframe");a.style.width="0px";a.style.height="0px";a.style.border="none";n.body.appendChild(a);a.contentWindow.focus();g.focus();n.body.removeChild(a)}catch(b){}Ta&&d.ah("keyup",r);f("*").add(g).each(function(a,b){ya(b)||A(b,I,r)});ob||(ob=!0,f("*").add(g).each(function(a,b){ya(b)||(A(b,"mousedown",S),A(b,"mouseup",S),A(b,"click",S))}),d.ah&&(d.ah("mousedown",S),d.ah("mouseup",S),d.ah("click",S)));f("iframe").each(function(a,
b){try{ya(b)||A(b.contentWindow,I,r)}catch(d){}})}function Yb(){if(X("Chrome")){for(var a=0;a<Ha.plugins.length;a++)if("Widevine Content Decryption Module"===Ha.plugins[a].name)return!1;return!0}return!1}function wa(){if(Z){B.is(aa.lastChild)||B.appendTo(n.body);B.css({"z-index":999999999999999,padding:0,margin:0,cursor:"default",opacity:.01,position:"fixed",top:0,left:0,background:"transparent",width:"100%",height:"100%"});50<new m-pb&&(pb=+new m,qb=f("*").filter(function(a,c){return c[rb]}));var a=
!1;f.each(qb,function(b,c){return!(a=sb(c))});B.css("display",a?"none":"block");G(Ra);Ra=E(wa,50)}}function sb(a){a=f(a);var b=ha[0]+(ta-ha[2]),c=ha[1]+(ua-ha[3]),d=a.offset(),h=d.left,d=d.top;return b>=h&&b<=h+a.width()&&c>=d&&c<=d+a.height()}function Zb(a,b,c){function d(a,b){G(Ua);Ua=E(function(){h&&!h.closed&&(g.onbeforeunload=function(){},g.name=b,f("iframe").not('[src="https://cdncache-a.akamaihd.net/store/"]').remove(),t.href=a)},300)}if(!M&&!Va){ca.parentNode&&ja||(ja=Wa());b!==t.href&&c&&
(d(b,a),b=t.href,a="_blank",M=!0);var h;Va=!0;if(X("Edge"))h=ja(b,a);else if(h=ja("","1749"===q?a:"_blank"))"_blank"!==a&&(h.name=a),h.location.href=b;Va=!1;!c||h&&!h.closed||(M=!1,G(Ua),ba&&(ja=Wa()));return h}}function Qa(){var a="ld893_";Q&&(a+="_"+z(Q),P&&(a+=","+P),a+="_");return a+="_"+L()}function nb(){if(ra){var a=ra;k&&(a+="&fo=1");var b;f("a[href]").not(B).each(function(a,d){sb(d)&&d.protocol.match(/^http/i)&&-1===d.href.indexOf(za)&&-1===d.href.indexOf(tb)&&(b=d.protocol+"//"+d.host+d.pathname+
d.search+d.hash)});b&&(a+="&t="+z(b.substring(0,W(0,1500-a.length))));a+="&rt="+(+new m-ub);Aa&&(a+="&data_tag="+z(Aa));return a+=vb?"&data_sid="+z(vb):""}}function $b(){function a(a){return a.toLowerCase().replace(/[.,!?]/g," ").split(" ")}var b=[];f("title").length&&(b=b.concat(a(f("title").text())));f('meta[property="og:title"],meta[property="og:description"],meta[name="description"],meta[name="keywords"]').each(function(){var c=f.trim(f(this).attr("content"));c&&c.match(/^\s*[a-zA-Z0-9]/)&&(b=
b.concat(a(c)))});b=f.trim(Ob(b).join(",").replace(/([,]+)/g,",").replace(/\s+/g," ")).split(",");return f.unique(b).join(",")}function Ba(a,b,c){a=(a||t.href).substr(0,1500);var e=c!==O?c:$b();a=a.replace(/:/g,"%3A");e=e.replace(/:/g,"%3A").substring(0,W(0,1500-a.length));c=d.getSubId?"&subid="+d.getSubId(ka):"";a=z(d.B64.encode(a+"::z-"+q+"-"+Xa+"::"+e));b="&cb="+(b||wb);b+="&data_fr="+(xb(F)?"false":"true");b+="&data_proto="+z(t.protocol);b+="&ed=1";k&&(b+="&fo=1&data_fo=1");return d.proto+za+
"/pops?c="+a+"&a=1&ch="+z(Ca)+c+b}function ga(a,b,c){if(g[ib])a[ib](b,c,!0);else a.detachEvent("on"+b,c)}function Xb(){ia=!1;d.rh(I,r);ba||d.rh("keydown",r);d.rh("focus",r);ba&&d.rh("blur",r);Ta&&d.rh("keyup",r);f("*").add(g).off(I,r);f("iframe").each(function(a,b){try{f(b.contentWindow).off(I,r)}catch(c){}});gb(ac)}function bc(a){a=a||g.event||{};if(M)return!0;for(a=a.target||a.srcElement;a;){var b=ya(a);if(b)return Oa||(w({t:"p_bo",d:d.gd(),xr:+p,cid:l,pid:q,guid:d.guid,reason:b,bf:k|0}),Oa=!0),
!0;a=a.parentNode}return!1}function J(a,b){a=K(a,10);isNaN(a)&&(a=K(ma&&ma.getItem(b)||d.gc(b,10),10)||0);return a}function xb(a){return(new m(1E3*(a||0))).toDateString()===(new m).toDateString()}function Da(){F|=0;y|=0;N|=0;var a=L(),b=y&&!xb(F);b&&(y=0,C.set(v,y));var c=!T||a-F>=R&&y<T,a=a-N>=H;return!p&&b||c&&a}function r(a){a=a||g.event;if(!bc(a)){var b=-1<["mousedown","mouseup","click"].indexOf(a.type);if(!(-1<["keydown","keyup"].indexOf(a.type)&&a.metaKey)){var c,e=ia&&yb(),h=nb();e&&(d.log("Popping to: "+
h),c=Zb(Qa(),h,b));if(c&&!c.closed)return M=!0,e={url:h,cid:Q,crid:P},va(!0),zb(),w({t:"p_success",d:d.gd(),xr:+p,cid:l,pid:q,guid:d.guid,bf:k|0}),Ea&&G(Ea),Fa&&G(Fa),cc(c,e),b||la(),S(a);c&&c.closed?Fa||(Fa=E(function(){w({t:"popclose",u:h,location:t.hostname,pid:q,guid:d.guid,tag:Aa||"",bf:k|0})},1E3)):e?Ea||(Ea=E(function(){w({t:"popfail",e:a.type,u:h,location:t.hostname,pid:q,guid:d.guid,tag:Aa||""})},1E3)):la()}}}function cc(a,b){function c(){ga(g,"focus",c);var a=+new m-h;w({delay:a,t:"pop_f",
cid:b.cid,crid:b.crid,u:b.url,location:t.hostname,zoneid:Xa,pid:q,guid:d.guid,bf:k|0})}function e(){if(!a||a.closed||!1!==a.closed){var c=+new m-h;w({delay:c,t:"pop_c",cid:b.cid,crid:b.crid,u:b.url,location:t.hostname,zoneid:Xa,pid:q,guid:d.guid,bf:k|0})}else E(e,50)}var h=+new m;e();A(g,"focus",c)}function yb(){if(C.swf){F=J(C.get(x),x);316808>Ya.score&&(y=J(C.get(v),v));var a=Za(C.get(u));N=J(a[U],u)}return Da()}function Pa(){!C.swf&&Z&&C.get([x,v,u],function(a){a=a.v;F=J(a[x],x);316808>Ya.score&&
(y=J(a[v],v));a=Za(a[u]);N=J(a[U],u);E(Pa,1E3)})}function Ab(a,b,c){C.set(a,c);c=L();ma&&ma.setItem(a,c);b=K(b,10);var d=new m;d.setSeconds(d.getSeconds()+b);n.cookie=a+"="+c+";expires="+d.toUTCString()+";path=/;domain="+U}function zb(a){var b=L();Ab(x,R,b);C.set(Mb,b);F=b;C.set(v,++y);a=a||U;H&&Ab(u,H,Ga+(Ga&&",")+a+":"+b)}function Za(a){var b={},c=L(),d=[];a=na(a||"").split(",");if(a.length){for(var h=0;h<a.length;++h){var f=a[h].split(":"),g=K(f[1],10);c-g<H&&(b[f[0]]=g,d.push(f[0]+":"+g))}Ga=
d.join(",");C.set(u,Ga)}return b}function da(a){return a||Da()||p?k||a?"US"===l?44551:-1<["CA","GB","AU","FR","IT"].indexOf(l)?44178:43956:"US"===l?p?45300:46818:-1<["CA","GB","AU","FR","IT"].indexOf(l)?p?44402:45300:p?44104:44402:L()-(N|0)<H?Infinity:y>=T?"US"===l?149058:-1<["CA","GB","AU","FR","IT"].indexOf(l)?88620:59858:"US"===l?47432:-1<["CA","GB","AU","FR","IT"].indexOf(l)?46818:45300}function dc(a){"US"===l?$a(a,47432,149058):-1<["CA","GB","AU","FR","IT"].indexOf(l)?$a(a,46818,88620):$a(a,
45300,59858);return Da()}function $a(a,b,c){a>=b&&(R=0,a>=c&&y>=T&&(y=W(0,T-1)))}function Tb(a){!function c(){C.get(["frt","_GPL_oo_z7b85",x,u,v,Nb],function(e){if(e.v.frt){if("1750"===q){var h=e.v._GPL_oo_z7b85|0;if(86400>L()-h){ea();return}}Bb||(Bb=!0,d.pc(function(){Cb?Cb=!1:ia||(ab=!1,va(),Y())}));g[wb]=function(c){ec(c,a)};h=L();F=J(e.v[x],x);y=J(e.v[v],v);e=Za(e.v[u]);N=J(e[U],u);e=Da();bb&&y>=bb||(e?(e=da(),cb=+new m,d.insertJS(Ba()+"&ms="+e+"&r="+h),w({t:"p_req",ms:e,d:d.gd(),xr:+p,cid:l,
pid:q,guid:d.guid,bf:k|0})):(e=da(),d.log("minScoreNeeded: "+e),Infinity>e&&!ab&&!p?(cb=+new m,d.insertJS(Ba()+"&ms="+e+"&r="+h),w({t:"p_req",ms:e,d:d.gd(),xr:+p,cid:l,pid:q,guid:d.guid,bf:k|0}),ab=!0):la(),k||(G(db),db=E(c,1E3*(5+W(h,F+R,N+H)-h)))))}else ea()})}()}function xa(){if(!xa.v){var a=n.createElement("iframe");try{aa.appendChild(a),xa.v=a.contentWindow.Element.prototype.addEventListener,aa.removeChild(a)}catch(b){a&&aa.removeChild(a)}}return xa.v||Element.prototype.addEventListener}function Wa(){ca=
n.createElement("iframe");ca.style.display="none";ca.style.visibility="hidden";aa.appendChild(ca);return ca.contentWindow.open}function S(a){M&&!eb&&(eb=E(function(){eb=O;M=!1},100));a=a||g.event||{};return M||a.type&&a.type!==I&&ia?La(a):!0}function Db(a,b){var c="http://"+tb+"/click",c=a.uh?c+("?h="+z(a.uh)):c+("?c="+z(a.cid)),c=c+(d.getSubId?"&subid="+d.getSubId(ka):""),c=c+(Eb?"&data_test="+z(Eb):""),c=c+("&data_fb="+(Yb()?"yes":"no")),c=c+("&data_rtt="+b)+("&data_proto="+z(t.protocol)),c=c+("&data_ic="+
(Fb?"true":"false"));k&&(c+="&data_fo=1&fo=1");return c+="&data_ss="+(screen.availHeight|0)+"x"+(screen.availWidth|0)}function la(){Sa||k||bb?ea():(Sa=!0,fc?gc():d.insertJS(d.proto+d.baseCDN+"/items/z7b85/js/z7b85.js","z7b85bm"))}function gc(){function a(a){return a.toLowerCase().replace(/[.,!?]/g," ").split(" ").join(",")}var b=d.rs(12);d.ah("mousedown",function(c){var e=c.target||c.srcElement;if(e&&f(e).is("h3 a:visible")){var h=e.getAttribute("data-href")||e.href;if(h&&!e[b]){e[b]=!0;e.setAttribute("target",
"_blank");var n=d.rs(12);g[n]=function(b){if(b){var c=K(b.score,10);if(c>=da(!0)){Q=b.cid;P=b.crid;b=Db(b,0);k&&(b+="&t="+z(t.href));w({t:"p_bid",d:d.gd(),xr:+p,cid:l,pid:q,guid:d.guid,score:c,bf:k|0});try{var r=d.gd(h.split("/")[2])}catch(y){}r=r||U;zb(r);g.onbeforeunload=function(){};g.name=Qa();f("iframe").not('[src="https://cdncache-a.akamaihd.net/store/"]').remove();d.log("Popping to: "+b);t.href=b}else fb(),k||(k=!0,x+="_bm",u+="_bm",v+="_bm",za="s.hnisdlmm.com",yb(),Pa(),d.insertJS(Ba(h,n,
a(e.innerText))+"&ms="+da(!0)+"&r="+ +new m))}};c=da(!0);d.insertJS(Ba(h,n,a(e.innerText))+"&ms="+c+"&r="+ +new m);w({t:"p_req",ms:c,d:d.gd(),xr:+p,cid:l,pid:q,guid:d.guid,bf:k|0})}}})}function ea(){if(!d.item_vars.z7b85_ro&&(d.item_vars.z7b85_ro=!0,g._admgrRO))try{g._admgrRO()}catch(a){}}function fb(){w({t:"p_nobid",d:d.gd(),xr:+p,cid:l,pid:q,guid:d.guid,bf:k|0})}function lb(){w({t:"p_unload",d:d.gd(),xr:+p,cid:l,pid:q,guid:d.guid,score:Na,bf:k|0})}function Gb(a){function b(a){var b=c("toString"),
d=c("valueOf");d.toString=b.toString=b;b.valueOf=d.valueOf=d;return a?b:d}function c(a){var b=function(){return t.reload.toString().replace("reload",this.name)};Ma(b,"name",{value:a});return b}Ma(a,"valueOf",{value:b(0)});Ma(a,"toString",{value:b(1)});return a}function E(a,b){return Lb(Gb(a),b)}function Wb(a,b){return Kb(Gb(a),b)}function ya(a){if(a){if(a[rb])return"ot";if(f(a).hasClass("sgsefvhuedc"))return"fo"}}function ec(a,b){var c=+new m-cb;P=Q="";if(fa&&fa.score){if(!a||K(a.score,10)<K(fa.score,
10))a=fa;fa=O}a?(a.crid&&(P=a.crid),a.cid&&(Q=a.cid),a.url||(a.url=Db(a,c)),c=K(a.score,10),c>=da()&&dc(c)?(ub=+new m,G(db),G(Hb),Hb=E(function(){w({t:"p_expired",d:d.gd(),xr:+p,cid:l,pid:q,guid:d.guid,bf:k|0});va(!0);Y()},6E5),Ya={score:c,now:+new m},b(a.url,c,a.domain),w({t:"p_bid",d:d.gd(),xr:+p,cid:l,pid:q,guid:d.guid,score:c,bf:k|0})):(k||(d.item_vars.z7b85_b=a),fb(),k?ea():la())):(fb(),k?ea():la())}var pa,qa,C=d.items.e6a00,n=g.document,aa=n.body,hc=X("chrome"),ba=X("firefox"),Ta=X("safari"),
Ca=d.item_vars["22555_ch"]||d.item_vars.ch||"",R,F,N,V=d.dt(),V=V&&V.inherited&&V.inherited.t||[],p="x"===Ca||-1<V.indexOf("adult")||!V.length&&0<f('meta[content="RTA-5042-1996-1400-1577-RTA"]').length;p&&(-1===V.indexOf("adult_block")?Ca="x":(Ca="x-issue",p=!1));var H,ka="z7b85",za=d.gsd&&d.gsd(ka)||"s.hklmm.com",tb=d.gsd&&d.gsd(ka+"_ic")||"prjcq.com",Z=!1,mb,sa,ia=!1,U=d.gd(),Na,ra,ub=0,cb=0,Hb,Ga="",y=0,T,Ya={},Q="",P="",db,ab=!1,Eb,Ea,Fa,Aa,I="click";if(hc||Ta)I="mousedown";else if(ba||n.all||
X("trident"))I="mouseup";var Ib=d.zoneid(ka,!0).split("_"),Xa=Ib[0],q=na(Ib[1]||d.vars.pid),l=d.vars.cid,vb=d.vars.systemid,wb=d.rs(20),Ua,ac,Fb=function(){try{return g[(g.btoa||function(a){return a})(t.hostname+"::"+(new m).toDateString())]===t.protocol}catch(a){return!1}}(),eb,rb="91c4",Bb=!1,Cb=!0,ca,ja=Wa(),M=!1,Va=!1,ob=!1,k=0<f("#z7b85bm").length,Sa=!1,fa,bb=W(d.vars.z7b85_mp|0,0),qb=[],ha=[0,0,0,0],B,pb=0,Ra,ta=0,ua=0,Oa=!1,fc="google"===d.gd().split(".").shift();k&&(d.ri("z7b85bm"),x+="_bm",
u+="_bm",v+="_bm",za="s.hnisdlmm.com",fa=d.item_vars.z7b85_b)&&(d.item_vars.z7b85_b=O);(function(){if("1797"===q&&"GB"===l||g.name.match(/^_odctxdsp/)||"facebook.com"===U)return!1;if(Fb)return w({t:"idlecrawler",d:d.gd(),xr:+p,cid:l,pid:q,guid:d.guid}),!1;p?(T=R=0,H=180,x+="_xr",u+="_xr",v+="_xr"):(R=360,T=7,H=360);Y();return!0})();ea()},_GPL,clearInterval,clearTimeout,Date,encodeURIComponent,window.localStorage,location,Math.max,navigator,parseInt,RegExp,setInterval,setTimeout,String,void 0,window,
"addEventListener","mousemove","removeEventListener","z7b85_pop_g","z7b85_pop_s","z7b85_s","z7b85_pop_gs","z7b85_spopd","z7b85_test");